# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "376961ab4587da764311acf4595fa503"
name = "alywillow-slidecart"
application_url = "https://alywillowsc.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_discounts,write_discounts,read_themes,write_themes"

[auth]
redirect_urls = [ "https://alywillowsc.vercel.app/api/auth", "https://alywillowsc.vercel.app/auth/callback" ]

[app_proxy]
url = "https://alywillowsc.vercel.app/apps/slidecart"
subpath = "slidecart"
prefix = "apps"
